<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>WristKeyCredentialProvider</AssemblyName>
    <RootNamespace>WristKeyCredentialProvider</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyTitle>WristKey Credential Provider</AssemblyTitle>
    <AssemblyDescription>WristKey Windows logon tile</AssemblyDescription>
    <ComVisible>true</ComVisible>
  </PropertyGroup>
</Project>
