<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <OutputType>Library</OutputType>
    <AssemblyName>WristKeyCredentialProvider</AssemblyName>
    <RootNamespace>WristKey.CredentialProvider</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lithnet.CredentialProvider" Version="1.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Runtime.InteropServices" />
    <Reference Include="System.IO.Pipes" />
  </ItemGroup>
</Project>
