<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>WristKeyCredentialProvider</AssemblyName>
    <RootNamespace>WristKeyCredentialProvider</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <ComVisible>true</ComVisible>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyTitle>WristKey Credential Provider</AssemblyTitle>
    <AssemblyDescription>WristKey Windows logon tile</AssemblyDescription>
    <LangVersion>7.3</LangVersion>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>
</Project>
