[package]
name = "wristkey-daemon"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
name = "wristkey_daemon"
path = "src/lib.rs"

[features]

[dependencies]
wristkey-core = { path = "../core" }
wristkey-ble = { path = "../ble" }
tokio = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
